### PR TITLE
Add animation style option

### PR DESCRIPTION
**Pull request by idanlevi1**
Especially for change animation color
Solve issue #151

### CODE REVIEW

**Comment by idanlevi1** [comment]
@tux-tn @nonotest @mfrachet @thiagomorales

**Comment by SrBrahma** [comment]
Needed! I have a colored view and the animation color doesn't fit well on it

**Comment by idanlevi1** [comment]
@mfrachet  Why?

**Comment by mfrachet** [comment]
Woops, sorry, it was in the bulk of dependabots one , I did not see 😅

**Comment by idanlevi1** [comment]
> Woops, sorry, it was in the bulk of dependabots one , I did not see 😅

So you can merge it? very helpful

**Comment by mfrachet** [comment]
Sure, but keep in mind that I don't work on this project anymore :) https://github.com/mfrachet/rn-placeholder/issues/179 . I won't invest time on it anymore, so feel free to fork it or to comment on the issue 😊

**Review by mfrachet — APPROVED** [review]

**Comment by idanlevi1** [comment]
@mfrachet can you add `animationStyleProps` to `README.md`?

**Pull request merged**
