### PR TITLE
Fixing useNativeDriver warning

### PR DESCRIPTION
**Pull request by mfrachet**
Should fix https://github.com/mfrachet/rn-placeholder/issues/120

### CODE REVIEW

**Comment by NelsonPRSousa** [comment]
Is is possible to set useNativeDriver to true? Without useNativeDriver, all the work is done on the JS thread, causing frame drops in our applications. I know there are limitations when to use useNativeDriver, but maybe we could improve this somehow 🤷‍♂️ 

Thanks for your work 🚀

**Comment by mfrachet** [comment]
I can't do this on every single animations since useNativeDriver works _only_ for transition and opacity things :/

There's already an issue to move the animation on the main thread instead https://github.com/mfrachet/rn-placeholder/issues/99 but I honestly don't have time to rework this for now :/

**Comment by NelsonPRSousa** [comment]
No worries, maybe someone with enough experience can take a look 🚀 

Thanks for fixing!

**Comment by NelsonPRSousa** [comment]
@mfrachet I think we can merge to get rid of this warning. Maybe in the future someone can have an idea to avoid block the JS thread, but I believe it should be addressed in some other PR 👍

**Comment by mfrachet** [comment]
Yep, just having an issue with test that are not running anymore for some reasons here :)

**Comment by FadiAboMsalam** [comment]
@mfrachet do you have any idea when this will be merged 🤔 ?

**Comment by mfrachet** [comment]
@FadiAboMsalam when I'll figure out why testing doesn't work anymore :(

**Comment by tranvanquang** [comment]
How can I fix It? I think u should using useNativeDriver same useNativeDriver in animation?

**Comment by mfrachet** [comment]
Closing in favor of https://github.com/mfrachet/rn-placeholder/pull/124

**Pull request closed without merging**
