### PR TITLE
create ts definition for v2

### PR DESCRIPTION
**Pull request by jarvisluong**
I created this ts def in my own project so I would love to share it out 😄 

Try to resolve https://github.com/mfrachet/rn-placeholder/issues/74

### CODE REVIEW

**Comment by mfrachet** [comment]
A huge thanks for this 😊 !

Let me know when it's not in WIP anymore so that I can review 👌

**Comment by jarvisluong** [comment]
Yes!, I hope this will be done in this weekend 😄

**Comment by kevinhermawan** [comment]
Can't wait for this 😄

**Comment by jarvisluong** [comment]
@mfrachet I think the current typedef has covered all the exports. We can merge now and improve it later if necessary

**Comment by mfrachet** [comment]
It's okay to iterate on this 😊

**Pull request merged**
