### PR TITLE
Reverse Animation Direction for Shine and ShineOverlay

### PR DESCRIPTION
**Pull request by kareemgdiab**

### CODE REVIEW

**Comment by mfrachet** [comment]
Sorry for beeing that late to the party. I'm closing this for now and will try to work on that when I have time 🙏

**Comment by mfrachet** [comment]
It's now available in v3.0.3 . Thanks for your help here 🙏  https://github.com/mfrachet/rn-placeholder/pull/140

**Comment by kareemgdiab** [comment]
Thank you  🙏

**Comment by mfrachet** [comment]
No no, thank you and sorry for being that late 🙏

**Pull request closed without merging**
