### PR TITLE
refacto(PureComponent): Use PureComponent instead of stateless function HOC

### PR DESCRIPTION
**Pull request by flepretre**
Let's try this 😉

### CODE REVIEW

**Comment by mfrachet** [comment]
Do you know how we can bench both variants to get some feedback concerning performances ?

**Comment by burkeshartsis** [comment]
You may also consider using [Recompose](https://github.com/acdlite/recompose). All the benefits of stateless functional components + only what you need from component classes. See the [`pure`](https://github.com/acdlite/recompose/blob/master/docs/API.md#pure) and [`onlyUpdateForPropTypes`](https://github.com/acdlite/recompose/blob/master/docs/API.md#onlyupdateforproptypes) HOCs.

**Comment by mfrachet** [comment]
Thank you for the suggestion @burkeshartsis .

I'm not sure it's fully necessary to add an external dependency to make the same thing as what we're actually doing.

I'll probably consider using `recompose` inside others (and probably bigger) projects .

**Comment by flepretre** [comment]
@mfrachet we need to verify if the *PureComponent* will rerender each time once it's got children, like in non native React 😂 
If it does, I'm not quite sure this is an improvement anymore 🤔

**Pull request closed without merging**
